// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Preferences
#define _H_MainDirector_Preferences

static const JUtf8Byte* kPreferencesMenuStr =
"* %i EditToolBar::MainDirector"
;

enum {
	kEditToolBarCmd=1,
};


static void ConfigurePreferencesMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#r", JString::kNoCopy));
	}
};

#endif
