// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_MainDirector_Process
#define _H_MainDirector_Process

static const JUtf8Byte* kProcessMenuStr =
"* %b %i ShowAll::MainDirector %l"
"|* %i Stop::MainDirector"
"|* %i Kill::MainDirector %l"
"|* %i Pause::MainDirector"
"|* %i Continue::MainDirector %l"
"|* %i ReNice::MainDirector"
;

enum {
	kShowAllCmd=1,
	kEndCmd,
	kKillCmd,
	kPauseCmd,
	kContinueCmd,
	kReNiceCmd,
};

#ifndef _H_gpm_all_processes
#define _H_gpm_all_processes
#include "gpm_all_processes.xpm"
#endif
#ifndef _H_gpm_stop
#define _H_gpm_stop
#include "gpm_stop.xpm"
#endif
#ifndef _H_jx_af_image_jx_jx_edit_clear
#define _H_jx_af_image_jx_jx_edit_clear
#include <jx-af/image/jx/jx_edit_clear.xpm>
#endif
#ifndef _H_gpm_pause
#define _H_gpm_pause
#include "gpm_pause.xpm"
#endif
#ifndef _H_gpm_cont
#define _H_gpm_cont
#include "gpm_cont.xpm"
#endif
#ifndef _H_gpm_slow
#define _H_gpm_slow
#include "gpm_slow.xpm"
#endif

static void ConfigureProcessMenu(JXTextMenu* menu, const int offset = 0) {
	if (menu->IsEmpty() && JXMenu::GetDisplayStyle() == JXMenu::kWindowsStyle) {
		menu->SetShortcuts(JString("#p", JString::kNoCopy));
	}
	menu->SetItemImage(kShowAllCmd + offset, gpm_all_processes);
	menu->SetItemImage(kEndCmd + offset, gpm_stop);
	menu->SetItemImage(kKillCmd + offset, jx_edit_clear);
	menu->SetItemImage(kPauseCmd + offset, gpm_pause);
	menu->SetItemImage(kContinueCmd + offset, gpm_cont);
	menu->SetItemImage(kReNiceCmd + offset, gpm_slow);
};

#endif
