// This file was automatically generated by jx_menu_editor.
// Do not edit it directly!
// Any changes you make will be silently overwritten.

#ifndef _H_ProcessTable_Context
#define _H_ProcessTable_Context

static const JUtf8Byte* kContextMenuStr =
"* %i __EndProcess::ProcessTable"
"|* %i __KillProcess::ProcessTable %l"
"|* %i __PauseProcess::ProcessTable"
"|* %i __ContinueProcess::ProcessTable %l"
"|* %i __ReNiceProcess::ProcessTable"
;

enum {
	kContextEndCmd=1,
	kContextKillCmd,
	kContextPauseCmd,
	kContextContinueCmd,
	kContextReNiceCmd,
};

#ifndef _H_gpm_stop
#define _H_gpm_stop
#include "gpm_stop.xpm"
#endif
#ifndef _H_jx_af_image_jx_jx_edit_clear
#define _H_jx_af_image_jx_jx_edit_clear
#include <jx-af/image/jx/jx_edit_clear.xpm>
#endif
#ifndef _H_gpm_pause
#define _H_gpm_pause
#include "gpm_pause.xpm"
#endif
#ifndef _H_gpm_cont
#define _H_gpm_cont
#include "gpm_cont.xpm"
#endif
#ifndef _H_gpm_slow
#define _H_gpm_slow
#include "gpm_slow.xpm"
#endif

static void ConfigureContextMenu(JXTextMenu* menu, const int offset = 0) {
	menu->SetItemImage(kContextEndCmd + offset, gpm_stop);
	menu->SetItemImage(kContextKillCmd + offset, jx_edit_clear);
	menu->SetItemImage(kContextPauseCmd + offset, gpm_pause);
	menu->SetItemImage(kContextContinueCmd + offset, gpm_cont);
	menu->SetItemImage(kContextReNiceCmd + offset, gpm_slow);
};

#endif
