#!/bin/bash

PRE=$1;
if [[ -z $PRE ]]; then
	PRE=/usr/local;
fi

BIN=$PRE/bin;
DOC=$PRE/share/doc/drakon;
APP=$PRE/share/applications;
ICON=$PRE/share/pixmaps;

rm -f  $BIN/drakon;
rm -rf $DOC;
rm -f  `find $APP -name 'drakon*.desktop'`;
rm -f  `find $ICON -name 'drakon*.png'`;
