#!/bin/bash

PRE=$1;

BIN=$PRE/usr/bin;
DOC=$PRE/usr/share/doc/drakon;
APP=$PRE/usr/share/applications;
ICON=$PRE/usr/share/pixmaps;

rm -f  $BIN/drakon;
rm -rf $DOC;
rm -f  `find $APP -name 'drakon*.desktop'`;
rm -f  `find $ICON -name 'drakon*.png'`;
