name: nps-drakon
title: Drakon Process Manager
base: core20
version: "2.0.3"
license: GPL-3.0-or-later
source-code: https://github.com/jafl/drakon
issues: https://github.com/jafl/drakon/issues
contact: https://johnlindal.wixsite.com/aboutme/contact-me
summary: Drakon provides a simple way to manage UNIX processes.
description: |
  Drakon provides a simple way to manage UNIX processes.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: ppc64el

apps:
  nps-drakon:
    command: bin/desktop-launch nps-drakon
    plugs:
      - unity7
      - network
      - process-control

parts:
  nps-drakon:
    plugin: autotools
    source: .
    override-pull: |
      snapcraftctl pull
      sudo locale-gen en_US.UTF-8
      sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 100
    build-environment:
      - JX_ROOT: /snap/jx-application-framework/current
      - PATH: $PATH:$JX_ROOT/bin
      - LD_LIBRARY_PATH: $SNAPCRAFT_PART_INSTALL/lib:$SNAPCRAFT_PART_INSTALL/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAPCRAFT_PART_INSTALL/usr/lib:$SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    autotools-configure-parameters:
      - release
    organize:
      bin/drakon: bin/nps-drakon
    stage:
      - bin/nps-drakon
    build-packages:
      - g++-10
      - make
      - pkg-config
      - libx11-dev
      - libxinerama-dev
      - libxft-dev
      - libxmu-dev
      - libxi-dev
      - libx11-xcb-dev
      - libxcb-xfixes0-dev
      - libxcb-dri2-0-dev
      - libxpm-dev
      - libjpeg-dev
      - libpng-dev
      - libgd-dev
      - libace-dev
      - libicu-dev
      - libpcre3-dev
      - libxml2-dev
      - libboost-fiber-dev
      - xutils-dev
      - libdrm-dev
      - aspell
      - locales
    build-snaps:
      - jx-application-framework
    after: [ libs ]
  libs:
    plugin: nil
    stage-packages:
      - libace-6.4.5
      - libfontconfig1
      - libfreetype6
      - libgd3
      - libicu66
      - libjbig0
      - libjpeg-turbo8
      - libpng16-16
      - libtiff5
      - libwebp6
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxft2
      - libxinerama1
      - libxml2
      - libboost-fiber-dev
      - libxpm4
      - libxrender1
  launcher:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
