name: CI
on:
  push:
    branches: [ main ]
    tags: [ v* ]
  repository_dispatch:
    types: [ new-jx ]
  workflow_dispatch:
jobs:
  analyze-ubuntu:
    name: Ubuntu
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    uses: jafl/jx_application_framework/.github/workflows/app-analyze-ubuntu.yml@main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

  build-ubuntu:
    name: Ubuntu
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: jafl/jx_application_framework/.github/workflows/app-build-ubuntu.yml@main
    with:
      pkg-name: drakon

  build-fedora:
    name: Fedora
    uses: jafl/jx_application_framework/.github/workflows/app-build-fedora.yml@main
    with:
      pkg-name: drakon

  release:
    name: Release
    needs: [ build-ubuntu, build-fedora ]
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    uses: jafl/jx_application_framework/.github/workflows/app-release.yml@main
    with:
      pkg-name: drakon
      forge-name: nps-drakon
    secrets:
      api-key: ${{ secrets.SOURCEFORGE_API_KEY }}
      ssh-key: ${{ secrets.SOURCEFORGE_SSH_KEY }}
